# Generated by Django 3.2.3 on 2022-06-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('img', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('style', models.CharField(max_length=128)),
                ('top', models.CharField(max_length=128, null=True)),
                ('middle', models.CharField(max_length=128, null=True)),
                ('base', models.CharField(max_length=128, null=True)),
                ('smells', models.CharField(max_length=128, null=True)),
                ('attr', models.CharField(max_length=128)),
                ('creater', models.CharField(max_length=128)),
                ('labels', models.CharField(max_length=128)),
                ('rate', models.FloatField()),
                ('time', models.IntegerField()),
                ('smell_1', models.CharField(max_length=10)),
                ('smell_2', models.CharField(max_length=10)),
                ('smell_3', models.CharField(max_length=10)),
                ('smell_4', models.CharField(max_length=10)),
                ('smell_5', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
