# Generated by Django 3.2.3 on 2022-06-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('rate', models.FloatField()),
                ('user_love_score', models.FloatField(null=True)),
                ('weight1', models.FloatField(null=True)),
                ('year', models.IntegerField()),
                ('year_score', models.FloatField(null=True)),
                ('weight2', models.FloatField(null=True)),
                ('time', models.IntegerField()),
                ('time_score', models.FloatField(null=True)),
                ('weight3', models.FloatField(null=True)),
                ('qing_xin', models.FloatField(null=True)),
                ('gu_dian', models.FloatField(null=True)),
                ('nong_yu', models.FloatField(null=True)),
                ('fen_fang', models.FloatField(null=True)),
                ('ganju_score', models.FloatField(null=True)),
                ('lvye_score', models.FloatField(null=True)),
                ('shuisheng_score', models.FloatField(null=True)),
                ('fuqixiang_score', models.FloatField(null=True)),
                ('pige_score', models.FloatField(null=True)),
                ('xipu_score', models.FloatField(null=True)),
                ('muzhi_score', models.FloatField(null=True)),
                ('dongfang_score', models.FloatField(null=True)),
                ('meishi_score', models.FloatField(null=True)),
                ('huaxiang_score', models.FloatField(null=True)),
                ('guoxiang_score', models.FloatField(null=True)),
                ('style', models.CharField(max_length=128)),
                ('style_score', models.FloatField(null=True)),
                ('score', models.FloatField(null=True)),
            ],
        ),
    ]
