# Generated by Django 3.2.3 on 2022-06-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_rate_perfume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate_perfume',
            name='weight3',
        ),
        migrations.AddField(
            model_name='rate_perfume',
            name='year_prefer',
            field=models.FloatField(null=True),
        ),
    ]
