# Generated by Django 3.2.3 on 2022-06-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0003_auto_20220625_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='smell_1',
            new_name='main_smells',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='smell_2',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='smell_3',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='smell_4',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='smell_5',
        ),
    ]
