# Generated by Django 3.2.3 on 2022-06-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0004_auto_20220625_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate_perfume',
            name='fen_fang',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='gu_dian',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='nong_yu',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='qing_xin',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='weight1',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='weight2',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='year_prefer',
        ),
        migrations.AddField(
            model_name='rate_perfume',
            name='attr',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
