# Generated by Django 3.2.3 on 2022-06-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0005_auto_20220625_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate_perfume',
            name='dongfang_score',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='fuqixiang_score',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='ganju_score',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='guoxiang_score',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='huaxiang_score',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='lvye_score',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='meishi_score',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='muzhi_score',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='pige_score',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='shuisheng_score',
        ),
        migrations.RemoveField(
            model_name='rate_perfume',
            name='xipu_score',
        ),
    ]
