# Generated by Django 3.2.3 on 2022-06-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0006_auto_20220626_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
